/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBEP20__factory } from "./IBEP20__factory";
export { PerpetualRewardPool__factory } from "./PerpetualRewardPool__factory";
