/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TournamentControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bcoinTokenAddress"
      | "createTournament"
      | "enterMatch1v1"
      | "entryFeeFor1v1"
      | "matchCounter"
      | "matches"
      | "openTournaments"
      | "oracle"
      | "owner"
      | "reportMatchResult"
      | "reportTournamentResult"
      | "setSoloRewardPool"
      | "soloRewardPoolAddress"
      | "teamWallet"
      | "tournamentCounter"
      | "tournaments"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MatchCreated"
      | "MatchResultReported"
      | "PlayerEnteredQueue"
      | "PlayerJoinedTournament"
      | "PrizeDistributed"
      | "TournamentCreated"
      | "TournamentStarted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "bcoinTokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createTournament",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "enterMatch1v1",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "entryFeeFor1v1",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "matchCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "matches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "openTournaments",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reportMatchResult",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reportTournamentResult",
    values: [BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setSoloRewardPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "soloRewardPoolAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "teamWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tournamentCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tournaments",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "bcoinTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enterMatch1v1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entryFeeFor1v1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "matches", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "openTournaments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reportMatchResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportTournamentResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSoloRewardPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "soloRewardPoolAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "teamWallet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tournamentCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tournaments",
    data: BytesLike
  ): Result;
}

export namespace MatchCreatedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    players: AddressLike[],
    entryFee: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    players: string[],
    entryFee: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    players: string[];
    entryFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchResultReportedEvent {
  export type InputTuple = [matchId: BigNumberish, winner: AddressLike];
  export type OutputTuple = [matchId: bigint, winner: string];
  export interface OutputObject {
    matchId: bigint;
    winner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerEnteredQueueEvent {
  export type InputTuple = [player: AddressLike, entryFee: BigNumberish];
  export type OutputTuple = [player: string, entryFee: bigint];
  export interface OutputObject {
    player: string;
    entryFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerJoinedTournamentEvent {
  export type InputTuple = [tournamentId: BigNumberish, player: AddressLike];
  export type OutputTuple = [tournamentId: bigint, player: string];
  export interface OutputObject {
    tournamentId: bigint;
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrizeDistributedEvent {
  export type InputTuple = [winners: AddressLike[], totalPrize: BigNumberish];
  export type OutputTuple = [winners: string[], totalPrize: bigint];
  export interface OutputObject {
    winners: string[];
    totalPrize: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentCreatedEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    creator: AddressLike,
    capacity: BigNumberish,
    entryFee: BigNumberish
  ];
  export type OutputTuple = [
    tournamentId: bigint,
    creator: string,
    capacity: bigint,
    entryFee: bigint
  ];
  export interface OutputObject {
    tournamentId: bigint;
    creator: string;
    capacity: bigint;
    entryFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentStartedEvent {
  export type InputTuple = [tournamentId: BigNumberish];
  export type OutputTuple = [tournamentId: bigint];
  export interface OutputObject {
    tournamentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TournamentController extends BaseContract {
  connect(runner?: ContractRunner | null): TournamentController;
  waitForDeployment(): Promise<this>;

  interface: TournamentControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bcoinTokenAddress: TypedContractMethod<[], [string], "view">;

  createTournament: TypedContractMethod<
    [capacity: BigNumberish, entryFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  enterMatch1v1: TypedContractMethod<
    [entryFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  entryFeeFor1v1: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  matchCounter: TypedContractMethod<[], [bigint], "view">;

  matches: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, boolean] & {
        id: bigint;
        entryFee: bigint;
        winner: string;
        isActive: boolean;
      }
    ],
    "view"
  >;

  openTournaments: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  oracle: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  reportMatchResult: TypedContractMethod<
    [matchId: BigNumberish, winner: AddressLike],
    [void],
    "nonpayable"
  >;

  reportTournamentResult: TypedContractMethod<
    [tournamentId: BigNumberish, winners: AddressLike[]],
    [void],
    "nonpayable"
  >;

  setSoloRewardPool: TypedContractMethod<
    [_poolAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  soloRewardPoolAddress: TypedContractMethod<[], [string], "view">;

  teamWallet: TypedContractMethod<[], [string], "view">;

  tournamentCounter: TypedContractMethod<[], [bigint], "view">;

  tournaments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, boolean] & {
        id: bigint;
        creator: string;
        capacity: bigint;
        entryFee: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bcoinTokenAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createTournament"
  ): TypedContractMethod<
    [capacity: BigNumberish, entryFee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "enterMatch1v1"
  ): TypedContractMethod<[entryFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "entryFeeFor1v1"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "matchCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "matches"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, boolean] & {
        id: bigint;
        entryFee: bigint;
        winner: string;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "openTournaments"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reportMatchResult"
  ): TypedContractMethod<
    [matchId: BigNumberish, winner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reportTournamentResult"
  ): TypedContractMethod<
    [tournamentId: BigNumberish, winners: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSoloRewardPool"
  ): TypedContractMethod<[_poolAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "soloRewardPoolAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "teamWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tournamentCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tournaments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, boolean] & {
        id: bigint;
        creator: string;
        capacity: bigint;
        entryFee: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "MatchCreated"
  ): TypedContractEvent<
    MatchCreatedEvent.InputTuple,
    MatchCreatedEvent.OutputTuple,
    MatchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MatchResultReported"
  ): TypedContractEvent<
    MatchResultReportedEvent.InputTuple,
    MatchResultReportedEvent.OutputTuple,
    MatchResultReportedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerEnteredQueue"
  ): TypedContractEvent<
    PlayerEnteredQueueEvent.InputTuple,
    PlayerEnteredQueueEvent.OutputTuple,
    PlayerEnteredQueueEvent.OutputObject
  >;
  getEvent(
    key: "PlayerJoinedTournament"
  ): TypedContractEvent<
    PlayerJoinedTournamentEvent.InputTuple,
    PlayerJoinedTournamentEvent.OutputTuple,
    PlayerJoinedTournamentEvent.OutputObject
  >;
  getEvent(
    key: "PrizeDistributed"
  ): TypedContractEvent<
    PrizeDistributedEvent.InputTuple,
    PrizeDistributedEvent.OutputTuple,
    PrizeDistributedEvent.OutputObject
  >;
  getEvent(
    key: "TournamentCreated"
  ): TypedContractEvent<
    TournamentCreatedEvent.InputTuple,
    TournamentCreatedEvent.OutputTuple,
    TournamentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TournamentStarted"
  ): TypedContractEvent<
    TournamentStartedEvent.InputTuple,
    TournamentStartedEvent.OutputTuple,
    TournamentStartedEvent.OutputObject
  >;

  filters: {
    "MatchCreated(uint256,address[],uint256)": TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;
    MatchCreated: TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;

    "MatchResultReported(uint256,address)": TypedContractEvent<
      MatchResultReportedEvent.InputTuple,
      MatchResultReportedEvent.OutputTuple,
      MatchResultReportedEvent.OutputObject
    >;
    MatchResultReported: TypedContractEvent<
      MatchResultReportedEvent.InputTuple,
      MatchResultReportedEvent.OutputTuple,
      MatchResultReportedEvent.OutputObject
    >;

    "PlayerEnteredQueue(address,uint256)": TypedContractEvent<
      PlayerEnteredQueueEvent.InputTuple,
      PlayerEnteredQueueEvent.OutputTuple,
      PlayerEnteredQueueEvent.OutputObject
    >;
    PlayerEnteredQueue: TypedContractEvent<
      PlayerEnteredQueueEvent.InputTuple,
      PlayerEnteredQueueEvent.OutputTuple,
      PlayerEnteredQueueEvent.OutputObject
    >;

    "PlayerJoinedTournament(uint256,address)": TypedContractEvent<
      PlayerJoinedTournamentEvent.InputTuple,
      PlayerJoinedTournamentEvent.OutputTuple,
      PlayerJoinedTournamentEvent.OutputObject
    >;
    PlayerJoinedTournament: TypedContractEvent<
      PlayerJoinedTournamentEvent.InputTuple,
      PlayerJoinedTournamentEvent.OutputTuple,
      PlayerJoinedTournamentEvent.OutputObject
    >;

    "PrizeDistributed(address[],uint256)": TypedContractEvent<
      PrizeDistributedEvent.InputTuple,
      PrizeDistributedEvent.OutputTuple,
      PrizeDistributedEvent.OutputObject
    >;
    PrizeDistributed: TypedContractEvent<
      PrizeDistributedEvent.InputTuple,
      PrizeDistributedEvent.OutputTuple,
      PrizeDistributedEvent.OutputObject
    >;

    "TournamentCreated(uint256,address,uint8,uint256)": TypedContractEvent<
      TournamentCreatedEvent.InputTuple,
      TournamentCreatedEvent.OutputTuple,
      TournamentCreatedEvent.OutputObject
    >;
    TournamentCreated: TypedContractEvent<
      TournamentCreatedEvent.InputTuple,
      TournamentCreatedEvent.OutputTuple,
      TournamentCreatedEvent.OutputObject
    >;

    "TournamentStarted(uint256)": TypedContractEvent<
      TournamentStartedEvent.InputTuple,
      TournamentStartedEvent.OutputTuple,
      TournamentStartedEvent.OutputObject
    >;
    TournamentStarted: TypedContractEvent<
      TournamentStartedEvent.InputTuple,
      TournamentStartedEvent.OutputTuple,
      TournamentStartedEvent.OutputObject
    >;
  };
}
