-- SQL Script generated from SUPABASE_SCHEMA.md
-- This script creates the core tables: users, heroes, items, user_items, and user_bestiary.
-- It includes Foreign Key relationships and safety checks.

-- 1. Users Table
-- Stores player account information and global progression.
CREATE TABLE IF NOT EXISTS "users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "wallet_address" TEXT NOT NULL UNIQUE,
    "coins" INTEGER DEFAULT 1000,
    "account_level" INTEGER DEFAULT 1,
    "account_xp" INTEGER DEFAULT 0,
    "max_score" INTEGER DEFAULT 0,
    "flagged_cheater" BOOLEAN DEFAULT FALSE,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Heroes Table (referred to as nft_heroes in prompt)
-- Stores NFT and Non-NFT hero data.
CREATE TABLE IF NOT EXISTS "heroes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT REFERENCES "users"("id") ON DELETE CASCADE,
    "hero_type" TEXT CHECK (hero_type IN ('mock', 'nft')),
    "nft_id" INTEGER,
    "level" INTEGER DEFAULT 1,
    "xp" INTEGER DEFAULT 0,
    "rarity" TEXT CHECK (rarity IN ('Common', 'Rare', 'Super Rare', 'Legend', 'House')),
    "max_stage" INTEGER DEFAULT 1,
    "status" TEXT DEFAULT 'in_wallet',
    "hp" INTEGER DEFAULT 100,
    "damage" INTEGER DEFAULT 1,
    "speed" INTEGER DEFAULT 200,
    "bomb_size" REAL DEFAULT 1.0,
    "sprite_name" TEXT,
    "last_updated" TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Items Catalog (items)
-- Defines the base properties of items.
CREATE TABLE IF NOT EXISTS "items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL, -- 'weapon', 'consumable', 'material', 'fragment'
    "rarity" TEXT DEFAULT 'Common',
    "image_url" TEXT,
    -- 'stats' column added to support existing backend logic, though not explicitly in markdown table
    "stats" JSONB
);

-- 4. User Inventory (user_items)
-- Links users to items with quantities.
CREATE TABLE IF NOT EXISTS "user_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT REFERENCES "users"("id") ON DELETE CASCADE,
    "item_id" BIGINT REFERENCES "items"("id") ON DELETE CASCADE,
    "quantity" INTEGER DEFAULT 1,
    "equipped" BOOLEAN DEFAULT FALSE
);

-- 5. Bestiary (user_bestiary)
-- Tracks player kills per enemy type.
CREATE TABLE IF NOT EXISTS "user_bestiary" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT REFERENCES "users"("id") ON DELETE CASCADE,
    "enemy_type" TEXT NOT NULL,
    "kill_count" INTEGER DEFAULT 0
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_users_wallet ON "users"("wallet_address");
CREATE INDEX IF NOT EXISTS idx_heroes_user_id ON "heroes"("user_id");
CREATE INDEX IF NOT EXISTS idx_user_items_user_id ON "user_items"("user_id");
CREATE INDEX IF NOT EXISTS idx_user_bestiary_user_id ON "user_bestiary"("user_id");
