const fs = require('fs');
const path = require('path');

const envContent = `
# =================================================================
# BOMBDASH WEB3 - DEVELOPMENT ENVIRONMENT
# =================================================================
# This file is auto-generated by 'scripts/setup-env.js'.
# Do not modify it directly, as your changes may be overwritten.
# For permanent changes, please edit the generator script.
# =================================================================

# -- Blockchain Configuration --
# URL for the Binance Smart Chain Testnet RPC.
TESTNET_RPC_URL="https://data-seed-prebsc-1-s1.binance.org:8545/"

# -- Wallet Private Keys --
# WARNING: These are public keys for development and testing ONLY.
# DO NOT USE THESE KEYS FOR MAINNET OR TO STORE REAL ASSETS.

# The primary key used for deploying contracts.
PRIVATE_KEY="bdf9349232e6e5640836354d4b87531993549c8ea837faf8913de6293a6dd46b"

# The key for the oracle wallet, used for signing off-chain data.
ORACLE_PRIVATE_KEY="bdf9349232e6e5640836354d4b87531993549c8ea837faf8913de6293a6dd46b"

# -- Security Secrets --
# Secret key for signing and verifying JSON Web Tokens (JWT).
JWT_SECRET="bomb-dash-super-secret-key-2025!#"

# Secret key for accessing the admin panel.
ADMIN_SECRET="admin123"

# =================================================================
# CONTRACT ADDRESSES (AUTO-POPULATED BY DEPLOY SCRIPT)
# =================================================================
# These addresses are placeholders and will be automatically updated
# when you run the deployment script (scripts/deploy.js).
# =================================================================

# Address of the main TournamentController contract.
TOURNAMENT_CONTROLLER_ADDRESS=0x6ff88C9b5ac4A1551e7d095c546B4f090d0DFB8F

# Address of the PerpetualRewardPool contract for solo game rewards.
PERPETUAL_REWARD_POOL_ADDRESS=0x483E37AF1FC0cf5195330bc1C5675Df31d6f24Af

# Address of the WagerArena contract for PvP wagers.
WAGER_ARENA_ADDRESS=0x4Ac2c9B201879b8Bd8EFFec1f699A2C1A1517511

# Address of the BCOIN token contract on the testnet.
BCOIN_TESTNET_ADDRESS=0xb8B71994A25F816d5b3232f24Ce5ea0135cf3106

# Address of the Oracle's wallet, derived from the ORACLE_PRIVATE_KEY.
ORACLE_WALLET_ADDRESS=0x4a9e067d8324547E8B1Bd2aEEF1b8D2515424D9E

# Address of the HeroStaking contract.
HERO_STAKING_ADDRESS=0x0000000000000000000000000000000000000000

# Address of the MockHeroNFT contract.
MOCK_HERO_NFT_ADDRESS=0x0000000000000000000000000000000000000000
`;

const envPath = path.join(__dirname, '..', '.env');

try {
  fs.writeFileSync(envPath, envContent.trim());
  console.log(`✅ Successfully created .env file at: ${envPath}`);
} catch (error) {
  console.error(`❌ Error creating .env file: ${error.message}`);
  process.exit(1);
}