/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as perpetualRewardPoolSol from "./PerpetualRewardPool.sol";
export type { perpetualRewardPoolSol };
import type * as tournamentControllerSol from "./TournamentController.sol";
export type { tournamentControllerSol };
import type * as mocks from "./mocks";
export type { mocks };
export * as factories from "./factories";
export type { MockBCOIN } from "./mocks/MockBCOIN";
export { MockBCOIN__factory } from "./factories/mocks/MockBCOIN__factory";
export type { IBEP20 } from "./PerpetualRewardPool.sol/IBEP20";
export { IBEP20__factory } from "./factories/PerpetualRewardPool.sol/IBEP20__factory";
export type { PerpetualRewardPool } from "./PerpetualRewardPool.sol/PerpetualRewardPool";
export { PerpetualRewardPool__factory } from "./factories/PerpetualRewardPool.sol/PerpetualRewardPool__factory";
export type { TournamentController } from "./TournamentController.sol/TournamentController";
export { TournamentController__factory } from "./factories/TournamentController.sol/TournamentController__factory";
