/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PerpetualRewardPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bcoinTokenAddress"
      | "claimReward"
      | "dailyEmissionRate"
      | "gamesPlayedLastCycle"
      | "gamesPlayedThisCycle"
      | "lastCycleTimestamp"
      | "oracle"
      | "reportSoloGamePlayed"
      | "rewardPerGameThisCycle"
      | "startNewCycle"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "NewCycleStarted"
      | "RewardClaimed"
      | "SoloGamesReported"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "bcoinTokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyEmissionRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gamesPlayedLastCycle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gamesPlayedThisCycle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastCycleTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reportSoloGamePlayed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardPerGameThisCycle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startNewCycle",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "bcoinTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyEmissionRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gamesPlayedLastCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gamesPlayedThisCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastCycleTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reportSoloGamePlayed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardPerGameThisCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startNewCycle",
    data: BytesLike
  ): Result;
}

export namespace NewCycleStartedEvent {
  export type InputTuple = [
    timestamp: BigNumberish,
    rewardPerGame: BigNumberish
  ];
  export type OutputTuple = [timestamp: bigint, rewardPerGame: bigint];
  export interface OutputObject {
    timestamp: bigint;
    rewardPerGame: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [player: AddressLike, amount: BigNumberish];
  export type OutputTuple = [player: string, amount: bigint];
  export interface OutputObject {
    player: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SoloGamesReportedEvent {
  export type InputTuple = [count: BigNumberish];
  export type OutputTuple = [count: bigint];
  export interface OutputObject {
    count: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PerpetualRewardPool extends BaseContract {
  connect(runner?: ContractRunner | null): PerpetualRewardPool;
  waitForDeployment(): Promise<this>;

  interface: PerpetualRewardPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bcoinTokenAddress: TypedContractMethod<[], [string], "view">;

  claimReward: TypedContractMethod<
    [player: AddressLike, gamesPlayed: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  dailyEmissionRate: TypedContractMethod<[], [bigint], "view">;

  gamesPlayedLastCycle: TypedContractMethod<[], [bigint], "view">;

  gamesPlayedThisCycle: TypedContractMethod<[], [bigint], "view">;

  lastCycleTimestamp: TypedContractMethod<[], [bigint], "view">;

  oracle: TypedContractMethod<[], [string], "view">;

  reportSoloGamePlayed: TypedContractMethod<
    [gameCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  rewardPerGameThisCycle: TypedContractMethod<[], [bigint], "view">;

  startNewCycle: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bcoinTokenAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<
    [player: AddressLike, gamesPlayed: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dailyEmissionRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "gamesPlayedLastCycle"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "gamesPlayedThisCycle"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastCycleTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reportSoloGamePlayed"
  ): TypedContractMethod<[gameCount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardPerGameThisCycle"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "startNewCycle"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "NewCycleStarted"
  ): TypedContractEvent<
    NewCycleStartedEvent.InputTuple,
    NewCycleStartedEvent.OutputTuple,
    NewCycleStartedEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "SoloGamesReported"
  ): TypedContractEvent<
    SoloGamesReportedEvent.InputTuple,
    SoloGamesReportedEvent.OutputTuple,
    SoloGamesReportedEvent.OutputObject
  >;

  filters: {
    "NewCycleStarted(uint256,uint256)": TypedContractEvent<
      NewCycleStartedEvent.InputTuple,
      NewCycleStartedEvent.OutputTuple,
      NewCycleStartedEvent.OutputObject
    >;
    NewCycleStarted: TypedContractEvent<
      NewCycleStartedEvent.InputTuple,
      NewCycleStartedEvent.OutputTuple,
      NewCycleStartedEvent.OutputObject
    >;

    "RewardClaimed(address,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "SoloGamesReported(uint256)": TypedContractEvent<
      SoloGamesReportedEvent.InputTuple,
      SoloGamesReportedEvent.OutputTuple,
      SoloGamesReportedEvent.OutputObject
    >;
    SoloGamesReported: TypedContractEvent<
      SoloGamesReportedEvent.InputTuple,
      SoloGamesReportedEvent.OutputTuple,
      SoloGamesReportedEvent.OutputObject
    >;
  };
}
